// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBav6ggR8TjojDGpMn_S5q6govt1moP6I',
    appId: '1:944897367224:web:5123454a150d53ac56e84d',
    messagingSenderId: '944897367224',
    projectId: 'ineteam-2026',
    authDomain: 'ineteam-2026.firebaseapp.com',
    storageBucket: 'ineteam-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjGZGs2vSMC-OrHG03c4lNEK2Qqm_Ff4Q',
    appId: '1:178378132135:android:5fa2fc1e16be4e9dd02982',
    messagingSenderId: '178378132135',
    projectId: 'ineteam-2026',
    storageBucket: 'ineteam-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjGZGs2vSMC-OrHG03c4lNEK2Qqm_Ff4Q',
    appId: '1:178378132135:ios:21504259ab6505fed02982',
    messagingSenderId: '178378132135',
    projectId: 'ineteam-cloud',
    storageBucket: 'ineteam-cloud.firebasestorage.app',
    iosBundleId: 'com.example.ineteam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjGZGs2vSMC-OrHG03c4lNEK2Qqm_Ff4Q',
    appId: '1:178378132135:ios:21504259ab6505fed02982',
    messagingSenderId: '178378132135',
    projectId: 'ineteam-cloud',
    storageBucket: 'ineteam-cloud.firebasestorage.app',
    iosBundleId: 'com.example.ineteam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjGZGs2vSMC-OrHG03c4lNEK2Qqm_Ff4Q',
    appId: '1:178378132135:web:fd6a5782ce81bf1ad02982',
    messagingSenderId: '178378132135',
    projectId: 'ineteam-2026',
    authDomain: 'ineteam-2026.firebaseapp.com',
    storageBucket: 'ineteam-2026.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

}