// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBav6ggR8TjojDGpMn_S5q6govt1moP6I',
    appId: '1:944897367224:web:5123454a150d53ac56e84d',
    messagingSenderId: '944897367224',
    projectId: 'ineteam-2026',
    authDomain: 'ineteam-2026.firebaseapp.com',
    storageBucket: 'ineteam-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5wu1Sx1TiNfxff4kpGnMgaGDMsXFwmmE',
    appId: '1:944897367224:android:ff32751dec5491db56e84d',
    messagingSenderId: '944897367224',
    projectId: 'ineteam-2026',
    storageBucket: 'ineteam-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDzO8u4zg3l9tkj_a7U8VmBkXsAF-ROJA',
    appId: '1:944897367224:ios:d5912e8713fd9bd256e84d',
    messagingSenderId: '944897367224',
    projectId: 'ineteam-2026',
    storageBucket: 'ineteam-2026.firebasestorage.app',
    iosBundleId: 'com.example.ineteam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDzO8u4zg3l9tkj_a7U8VmBkXsAF-ROJA',
    appId: '1:944897367224:ios:d5912e8713fd9bd256e84d',
    messagingSenderId: '944897367224',
    projectId: 'ineteam-2026',
    storageBucket: 'ineteam-2026.firebasestorage.app',
    iosBundleId: 'com.example.ineteam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBav6ggR8TjojDGpMn_S5q6govt1moP6I',
    appId: '1:944897367224:web:3751bc487da0254556e84d',
    messagingSenderId: '944897367224',
    projectId: 'ineteam-2026',
    authDomain: 'ineteam-2026.firebaseapp.com',
    storageBucket: 'ineteam-2026.firebasestorage.app',
  );
}
